OPENAI_API_KEY = "sk-proj-KvEfc7ved2FpCBnC6x6UT3BlbkFJxec3eR0cGbrNIrQbrCUu"

[connections.snowflake]
user = "KIRTIBUDHAWANT1515"
password = "Aditya@05"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "tp79215.central-india.azure"
