# .streamlit/secrets.toml

# OpenAI API Key
OPENAI_API_KEY = "sk-...XTkA"

user = "KIRTIBUDHAWANT1515"
password = "Aditya@05"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "tp79215.central-india.azure"
