# .streamlit/secrets.toml

# OpenAI API Key
OPENAI_API_KEY = "sk-proj-85ZaCfYCZdCHCH5oCGrRT3BlbkFJ4RWsolE0jePk8Nng1RaC"

user = "KIRTIBUDHAWANT1515"
password = "Aditya@05"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "tp79215.central-india.azure"
